### ISSUE TITLE
log from TVHeadend showed that script doesn't report any EPG data

### ISSUE THREAD

**Issue by FabiB97** [nurtext/tv_grab_file_synology#2]
Log in TvHeadend shows following output 

`2018-12-11 14:39:51.000 xmltv: /usr/bin/tv_grab_file: grab /usr/bin/tv_grab_file`
`2018-12-11 14:39:51.001 spawn: Executing "/usr/bin/tv_grab_file"`
`2018-12-11 14:39:51.488 xmltv: /usr/bin/tv_grab_file: no output detected`
`2018-12-11 14:39:51.488 xmltv: /usr/bin/tv_grab_file: grab returned no data`

but when i open my EPG Source with the browser i get an xml with all infos

**Comment by nurtext** [comment]
The grab file only processes data from either a local or remote file with EPG data. The grab file is not a scraper for EPG data, you need to provide the EPG data using a local or remote file by yourself.

So…

1. TimeFor.tv is deprecated, the service is no longer available
2. Did you read README.md including the section "How to install" and modified the source?
3. If so, what variant did you choose (local or remote?)
4. Please paste the contents of your tv_grab_file

**Comment by FabiB97** [comment]
solved it by myself 😄 
i have a epg source which has login data at the end and that needed to be used in quotes like: `"http://example.com/path/to/epg.xml?username=xxxxxx&password=xxxx"`

because wget cutted the url at the "&" and no password was submitted

**Comment by Slim1399** [comment]
How can add url source !!?

**Comment by nurtext** [comment]
> How can add url source !!?

See README.md: This project has been abandoned and no further support will be given.
